export const story = [
  {
    id: "1",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been",
    translate: "",
    time: "00:00:00",
    type: "CAPTION",
  },
  {
    id: "2",
    text: "dummy text of the printing and typesetting",
    translate: "",
    time: "00:00:00",
    type: "CAPTION",
  },
  {
    id: "3",
    text: "asdfas",
    type: "CAPTION",
    time: "00:00:00",
    translate: "",
  },
  {
    id: "r",
    text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been",
    translate: "",
    time: "00:00:00",
    type: "CAPTION",
  },
  {
    id: "4",
    type: "REVIEW",
    time: "00:00:00",
    translatedDescription: "",
    learned: [{ word: "something", translation: "algo" }],
  },
  {
    id: "5",
    text: "dummy text of the printing and typesetting",
    translate: "",
    type: "CAPTION",
    time: "00:00:00",
  },
  {
    id: "11",
    text: "dummy text of the printing and typesetting",
    translate: "",
    type: "CAPTION",
    time: "00:00:00",
  },
  {
    id: "22",
    text: "dummy text of the printing and typesetting",
    translate: "",
    type: "CAPTION",
    time: "00:00:00",
  },
  {
    id: "23",
    text: "dummy text of the printing and typesetting",
    translate: "",
    type: "CAPTION",
    time: "00:00:00",
  },
];
